image:
  name: eu.gcr.io/savannah-emr/fls-image:11-06-21

stages:
  - test

sil_feed_tests:
  stage: test
  timeout: 10 minutes
  tags:
    - healthcloud-multi
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test/
    - lcov --remove coverage/lcov.info 'lib/**/*.g.dart' -o coverage/lcov.info
    - lcov --remove coverage/lcov.info 'lib/**/*.freezed.dart' -o coverage/lcov.info
    - genhtml -q -o coverage coverage/lcov.info
    - python3 check_coverage.py
