name: sil_feed
description: A package for viewing a user's feed
version: 0.0.1
author: abiud.orina@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_feed
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^0.21.0-nullsafety.0
  intl: ^0.17.0
  network_image_mock: ^2.0.0
  pdf_flutter:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/pdf_flutter.git
      ref: 0.0.1-nullsafety

  photo_view: ^0.11.1
  rxdart: ^0.26.0
  shimmer: ^2.0.0-nullsafety.0

  sil_themes:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
      ref: 0.0.5-nullsafety
  sil_ui_components:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_ui_components.git
      ref: 0.0.39-nullsafety

  visibility_detector: ^0.2.0-nullsafety.1

  youtube_player_flutter:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/youtube_player_flutter.git
      path: packages/youtube_player_flutter
      ref: 0.0.8-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mockito: ^5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
