name: user_feed
description: A package for viewing a user's feed
version: 0.1.50-nullsafety
homepage: https://github.com/savannahghi/user_feed
repository: https://github.com/savannahghi/user_feed
issue_tracker: https://github.com/savannahghi/user_feed/issues
documentation: https://github.com/savannahghi/user_feed/doc/readme.md

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  carousel_slider: ^4.0.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.0.1
  freezed: ^0.14.2
  freezed_annotation: ^1.1.0
  html: ^0.15.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^6.1.4
  mocktail_image_network: ^0.3.1 # for mocking
  photo_view: ^0.13.0
  rxdart: ^0.27.1
  shared_themes: ^0.1.0 # internal (formerly sil_themes)
  shared_ui_components: ^0.1.49-nullsafety # internal (formerly sil_ui_components)
  shimmer: ^2.0.0
  url_launcher: ^6.0.6
  visibility_detector: ^0.2.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.5.3
  mockito: ^5.0.10
  test:

flutter:
  uses-material-design: true
  assets:
    - packages/user_feed/assets/hide.svg
    - packages/user_feed/assets/pin.svg
    - packages/user_feed/assets/resolve.svg
    - packages/user_feed/assets/white_logo.png
    - packages/user_feed/assets/white_logo.svg
    - packages/user_feed/transparent_logo.svg
    - packages/user_feed/assets/zero-state.png
    - packages/user_feed/assets/swipe.png
    - packages/user_feed/assets/cover_action.svg
    - lib/assets/cover.png
