name: sil_feed
description: A package for viewing a user's feed
version: 0.0.1
author: abiud.orina@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/sil_feed

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  flutter_svg: ^0.19.1
  flutter_pdfview: ^1.0.4
  flutter_staggered_grid_view: '^0.3.2'
  intl: ^0.16.0
  pdf_flutter: ^1.1.3
  photo_view: ^0.10.3
  mockito: ^4.1.1

  rxdart: ^0.24.0
  shimmer: ^1.1.2
  youtube_player_flutter: ^7.0.0+7
  visibility_detector: ^0.1.5

  sil_themes:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_themes.git
      ref: 0.0.1
  sil_dumb_widgets:
    git:
      url: https://sil_dart_utils:xiFnpjLHssG76bpWxUb9@gitlab.slade360emr.com/optimalhealth/dart_utils/sil_dumb_widgets.git
      ref: 0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
